---
- hosts: webserver
  become: yes
  tasks:
    - name: display host name
      command: hostname -f
      register: myresult
    - name: displaying my result value
      debug:
        msg: "{{myresult}}"
        