---
- hosts: webserver
  become: yes
  tasks:
    - name: install java7 on redhat node
      yum:
        name: java-1.6.0-openjdk
        state: present
      when: ansible_os_family== "RedHat"    
    - name: install java8 on ubuntu node
      apt: 
        name: openjdk-8-jre
        state: present
      when: ansible_os_family== "Debian"
    