---
- hosts: webserver
  become: yes
  tasks:
    - name: install java7 on redhat node
      yum:
        name: "{{installingjavaonredhat}}"
        state: present
      when: ansible_os_family== "RedHat"    
    - name: install java8 on ubuntu node
      apt: 
        name: "{{installingjavaonubuntu}}"
        state: present
      when: ansible_os_family== "Debian"
    