---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    apt: 
      name: apache2
      state: present
  - name: start webserver
    service: 
      name: apache2
      state: started
  - name: install wildfly jboss server
    apt:
      name: wildfly
      state: present
  - name: start jboss sever
    service:
      name: wildfly
      state: started

